# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 680abe63b82349edfbbc0682537172a7e5d829c07d27445a1c8fb4bf128bd3ae5ea193f95558b3aeaefb33237ffed6f01071bae7530ae5d2be1b0e74ec433c85

test:
  secret_key_base: d1b5cf62c1121c6feadb56c1befeecaed3909d4a2d47eb9aeb826f7f4332707b1d070425365ac2190f8445d9c6fe11ebdc0849c1a45a6851f4398f232399e49e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
